variable "aws_region" {
  description = "AWS region for all resources"
  type        = string
  default     = "eu-central-1"
}

variable "project_name" {
  description = "Base name prefix for resources"
  type        = string
  default     = "touch-scrolling-web-app"
}

variable "github_owner" {
  description = "GitHub owner or org"
  type        = string
  default     = "felixd95"
}

variable "github_repo" {
  description = "GitHub repository name"
  type        = string
  default     = "touch-scrolling-web-app"
}

variable "github_branch" {
  description = "GitHub branch allowed to deploy"
  type        = string
  default     = "main"
}

variable "create_github_oidc_provider" {
  description = "Set true to create GitHub OIDC provider in this account"
  type        = bool
  default     = false
}

variable "existing_github_oidc_provider_arn" {
  description = "Existing GitHub OIDC provider ARN if create_github_oidc_provider is false"
  type        = string
  default     = ""
}

variable "existing_github_actions_deploy_role_arn" {
  description = "Existing GitHub Actions deploy role ARN to use for GitHub Actions OIDC assume-role"
  type        = string
  default     = ""
}

variable "frontend_bucket_name" {
  description = "Optional custom frontend bucket name. Leave empty for autogenerated"
  type        = string
  default     = ""
}

variable "sagemaker_endpoint_name" {
  description = "SageMaker endpoint used by triggerNextParameterSet lambda"
  type        = string
  default     = "touch-scrolling-active-learning-endpoint"
}

variable "sagemaker_container_image" {
  description = <<-EOT
    Full ECR image URI for the SageMaker inference container that runs
    sagemaker/active-learning-endpoint/code/inference.py. Leave empty to use
    the default prebuilt SageMaker PyTorch inference image (see
    data.aws_sagemaker_prebuilt_ecr_image.pytorch and
    var.sagemaker_pytorch_image_tag in sagemaker.tf).
  EOT
  type        = string
  default     = ""
}

variable "sagemaker_pytorch_image_tag" {
  description = <<-EOT
    Image tag for the prebuilt "pytorch-inference" ECR repository (see
    data.aws_sagemaker_prebuilt_ecr_image.pytorch in sagemaker.tf). Verify
    this tag still exists for var.aws_region before applying.
  EOT
  type    = string
  default = "2.1.0-cpu-py310"
}

variable "sagemaker_sklearn_image_tag" {
  description = <<-EOT
    Image tag for the prebuilt "sagemaker-scikit-learn" ECR repository (see
    data.aws_sagemaker_prebuilt_ecr_image.sklearn in sagemaker.tf). Verify
    this tag still exists for var.aws_region before applying - AWS
    periodically retires old image tags.
  EOT
  type        = string
  default     = "1.2-1"
}

variable "sagemaker_dlc_account_id" {
  description = "AWS account ID that hosts the Deep Learning Containers ECR images for most commercial regions"
  type        = string
  default     = "763104351884"
}

variable "sagemaker_serverless_memory_size_mb" {
  description = "Memory allocated to the SageMaker Serverless Inference endpoint (MB). Must be one of 1024, 2048, 3072, 4096, 5120, 6144."
  type        = number
  # NOTE: this AWS account's service quota for "Memory size in MB per
  # serverless endpoint" is currently only 3072 MB (confirmed via a
  # ResourceLimitExceeded error when attempting 6144). Requesting a quota
  # increase via AWS Service Quotas would be required before raising this.
  default = 3072
}

variable "sagemaker_serverless_max_concurrency" {
  description = "Maximum concurrent invocations for the SageMaker Serverless Inference endpoint"
  type        = number
  default     = 1
}

variable "tags" {
  description = "Common tags for all resources"
  type        = map(string)
  default = {
    ManagedBy = "terraform"
    Project   = "touch-scrolling-web-app"
  }
}
