variable "aws_region" {
  description = "AWS region for all resources"
  type        = string
  default     = "eu-central-1"
}

variable "project_name" {
  description = "Base name prefix for resources"
  type        = string
  default     = "touch-scrolling-web-app"
}

variable "github_owner" {
  description = "GitHub owner or org"
  type        = string
  default     = "felixd95"
}

variable "github_repo" {
  description = "GitHub repository name"
  type        = string
  default     = "touch-scrolling-web-app"
}

variable "github_branch" {
  description = "GitHub branch allowed to deploy"
  type        = string
  default     = "main"
}

variable "create_github_oidc_provider" {
  description = "Set true to create GitHub OIDC provider in this account"
  type        = bool
  default     = true
}

variable "existing_github_oidc_provider_arn" {
  description = "Existing GitHub OIDC provider ARN if create_github_oidc_provider is false"
  type        = string
  default     = ""
}

variable "frontend_bucket_name" {
  description = "Optional custom frontend bucket name. Leave empty for autogenerated"
  type        = string
  default     = ""
}

variable "sagemaker_endpoint_name" {
  description = "SageMaker endpoint used by triggerNextParameterSet lambda"
  type        = string
  default     = "touch-scrolling-active-learning-endpoint"
}

variable "tags" {
  description = "Common tags for all resources"
  type        = map(string)
  default = {
    ManagedBy = "terraform"
    Project   = "touch-scrolling-web-app"
  }
}
