variable "aws_region" {
  description = "AWS region for all resources"
  type        = string
  default     = "eu-central-1"
}

variable "project_name" {
  description = "Base name prefix for resources"
  type        = string
  default     = "touch-scrolling-web-app"
}

variable "github_owner" {
  description = "GitHub owner or org"
  type        = string
  default     = "felixd95"
}

variable "github_repo" {
  description = "GitHub repository name"
  type        = string
  default     = "touch-scrolling-web-app"
}

variable "github_branch" {
  description = "GitHub branch allowed to deploy"
  type        = string
  default     = "main"
}

variable "create_github_oidc_provider" {
  description = "Set true to create GitHub OIDC provider in this account"
  type        = bool
  default     = false
}

variable "existing_github_oidc_provider_arn" {
  description = "Existing GitHub OIDC provider ARN if create_github_oidc_provider is false"
  type        = string
  default     = ""
}

variable "existing_github_actions_deploy_role_arn" {
  description = "Existing GitHub Actions deploy role ARN to use for GitHub Actions OIDC assume-role"
  type        = string
  default     = ""
}

variable "frontend_bucket_name" {
  description = "Optional custom frontend bucket name. Leave empty for autogenerated"
  type        = string
  default     = ""
}

variable "sagemaker_endpoint_name" {
  description = "SageMaker endpoint used by triggerNextParameterSet lambda"
  type        = string
  default     = "touch-scrolling-active-learning-endpoint"
}

variable "sagemaker_container_image" {
  description = <<-EOT
    Full ECR image URI for the SageMaker inference container that runs
    sagemaker/active-learning-endpoint/code/inference.py. Leave empty to use
    the default AWS Deep Learning Containers PyTorch CPU image for
    var.aws_region. Verify the tag is still current at
    https://aws.github.io/deep-learning-containers/reference/available_images/
    before applying, since AWS periodically retires old image tags.
  EOT
  type        = string
  default     = ""
}

variable "sagemaker_dlc_account_id" {
  description = "AWS account ID that hosts the Deep Learning Containers ECR images for most commercial regions"
  type        = string
  default     = "763104351884"
}

variable "sagemaker_serverless_memory_size_mb" {
  description = "Memory allocated to the SageMaker Serverless Inference endpoint (MB). Must be one of 1024, 2048, 3072, 4096, 5120, 6144."
  type        = number
  # Set to the maximum: pip-installing botorch/gpytorch (plus their
  # scipy/linear_operator/pyro-ppl transitive dependencies) at container
  # cold start, on top of the already-loaded torch runtime, was likely
  # exceeding the previous 3072 MB budget and getting the model process
  # OOM-killed - which surfaces as the generic "model process exited" error.
  default = 6144
}

variable "sagemaker_serverless_max_concurrency" {
  description = "Maximum concurrent invocations for the SageMaker Serverless Inference endpoint"
  type        = number
  default     = 1
}

variable "tags" {
  description = "Common tags for all resources"
  type        = map(string)
  default = {
    ManagedBy = "terraform"
    Project   = "touch-scrolling-web-app"
  }
}
