scalar AWSDate
scalar AWSDateTime
scalar AWSJSON

schema {
  query: Query
  mutation: Mutation
}

type Query {
  listParticipants(filter: ModelParticipantFilterInput): ModelParticipantConnection!
}

type Mutation {
  createParticipant(input: CreateParticipantInput!): Participant
  updateParticipant(input: UpdateParticipantInput!): Participant
  appendParticipantAttemptBlock(participantId: ID!, block: AWSJSON!): Participant
  triggerNextParameterSet(participantId: ID!, attemptCount: Int!): TriggerNextParameterSetResult
}

type Participant {
  id: ID!
  firstName: String!
  lastName: String!
  email: String!
  birthDate: AWSDate!
  privateSmartphone: String!
  scrollHandPreference: String
  screenTimePerDay: String!
  attempts: AWSJSON
  currentParameterSet: AWSJSON
  nextParameterSet: AWSJSON
  createdAt: AWSDateTime
  updatedAt: AWSDateTime
}

type TriggerNextParameterSetResult {
  nextParameterSet: String!
}

type ModelParticipantConnection {
  items: [Participant]
}

input CreateParticipantInput {
  id: ID
  firstName: String!
  lastName: String!
  email: String!
  birthDate: AWSDate!
  privateSmartphone: String!
  scrollHandPreference: String
  screenTimePerDay: String!
  attempts: AWSJSON
  currentParameterSet: AWSJSON
  nextParameterSet: AWSJSON
}

input UpdateParticipantInput {
  id: ID!
  firstName: String
  lastName: String
  email: String
  birthDate: AWSDate
  privateSmartphone: String
  scrollHandPreference: String
  screenTimePerDay: String
  attempts: AWSJSON
  currentParameterSet: AWSJSON
  nextParameterSet: AWSJSON
}

input ModelIDInput {
  eq: ID
}

input ModelStringInput {
  eq: String
}

input ModelParticipantFilterInput {
  id: ModelIDInput
  email: ModelStringInput
}
